codecov:
  disable_default_path_fixes: true

coverage:
  status:
    project:
      enabled: yes
      target: auto
      threshold: 2%
    patch: yes
    changes: no
  precision: 2
  round: down
  range: "70...90"

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default

flags:
  eir:
    paths:
      - "/home/runner/work/fhircore/fhircore/android/eir"
  anc:
    paths:
      - "/home/runner/work/fhircore/fhircore/android/anc"
  engine:
    paths:
      - "/home/runner/work/fhircore/fhircore/android/engine"