codecov:
  notify:
    wait_for_ci: true
  max_report_age: off
  require_ci_to_pass: true
comment:
  behavior: default
  layout: "reach, diff, flags, files"
  show_carryforward_flags: false
coverage:
  precision: 1
  range:
  - 75.0
  - 100.0
  round: down
  status:
    changes: false
    patch:
      default:
        target: 60.0
    project:
      default:
        enabled: true
        target: auto
        threshold: 1.0
flag_management:
  default_rules:
    carryforward: true
ignore:
  - "**/androidTest"  # ignore all files in a folder called androidTest
  - "**/debug"  # ignore all files in a folder called debug
  - "**/test"  # ignore all files in a folder called test
