codecov:
  disable_default_path_fixes: true
  notify:
    wait_for_ci: true
  require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff, changes, uncovered, tree
  show_carryforward_flags: false
coverage:
  precision: 1
  range:
  - 75.0
  - 100.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        target: 60.0
    project:
      default:
        enabled: true
        target: auto
        threshold: 1.0
flags:
  engine:
    paths:
    - ^/home/runner/work/fhircore/fhircore/android/engine.*
  geowidget:
    paths:
    - ^/home/runner/work/fhircore/fhircore/android/geowidget.*
  quest:
    paths:
    - ^/home/runner/work/fhircore/fhircore/android/quest.*
github_checks:
  annotations: true
