codecov:
  notify:
    wait_for_ci: true
  max_report_age: off
  require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff, changes, uncovered, tree
  show_carryforward_flags: false
coverage:
  precision: 1
  range:
  - 75.0
  - 100.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        target: 60.0
    project:
      default:
        enabled: true
        target: auto
        threshold: 1.0
flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 60%
ignore:
  - "**/androidTest"  # ignore all files in a folder called androidTest
  - "**/debug"  # ignore all files in a folder called debug
  - "**/test"  # ignore all files in a folder called test
