codecov:
  disable_default_path_fixes: yes
  notify:
    after_n_builds: 3
    wait_for_ci: yes

coverage:
  status:
    project:
      enabled: yes
      target: auto
      threshold: 1%
    patch: 
      target: 60%
    changes: no
  precision: 1
  round: down
  range: "75...100"

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default

flags:
  engine:
    paths:
      - "/home/runner/work/fhircore/fhircore/android/engine"
  geowidget:
    paths:
      - "/home/runner/work/fhircore/fhircore/android/geowidget"
  quest:
    paths:
      - "/home/runner/work/fhircore/fhircore/android/quest"
