codecov:
  disable_default_path_fixes: true

coverage:
  status:
    project:
      enabled: yes
      target: auto
      threshold: 1%
    patch:
      target: 60%
    changes: no
  precision: 1
  round: down
  range: "75...100"

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default

flags:
  eir:
    paths:
      - "/home/runner/work/fhircore/fhircore/android/eir"
  anc:
    paths:
      - "/home/runner/work/fhircore/fhircore/android/anc"
  engine:
    paths:
      - "/home/runner/work/fhircore/fhircore/android/engine"
  quest:
    paths:
      - "/home/runner/work/fhircore/fhircore/android/quest"
