codecov:
  disable_default_path_fixes: true

coverage:
  status:
    project:
      enabled: yes
      target: auto
      threshold: 2%
    patch: yes
    changes: no
  precision: 2
  round: down
  range: "70...90"

fixes:
  - "/home/runner/work/fhircore/fhircore/android/anc::"

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default
