codecov:
  disable_default_path_fixes: true

coverage:
  status:
    project: no
    patch: yes
    changes: no
  precision: 2
  round: down
  range: "70...100"

fixes:
  - "/home/runner/work/fhircore/fhircore/android/eir::"

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default
