export default {
  '062d2070': [() => import(/* webpackChunkName: '062d2070' */ '@site/docs/fhir-core-documetation.md'), '@site/docs/fhir-core-documetation.md', require.resolveWeak('@site/docs/fhir-core-documetation.md')],
  '0e384e19': [() => import(/* webpackChunkName: '0e384e19' */ '@site/docs/intro.md'), '@site/docs/intro.md', require.resolveWeak('@site/docs/intro.md')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  'a5f8aaf7': [() => import(/* webpackChunkName: 'a5f8aaf7' */ '@site/docs/in-app-reporting.md'), '@site/docs/in-app-reporting.md', require.resolveWeak('@site/docs/in-app-reporting.md')],
  'c3ab6d08': [() => import(/* webpackChunkName: 'c3ab6d08' */ '/home/smutuku/Documents/Github/fhircore/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json'), '/home/smutuku/Documents/Github/fhircore/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json', require.resolveWeak('/home/smutuku/Documents/Github/fhircore/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json')],
  'd7e086c9': [() => import(/* webpackChunkName: 'd7e086c9' */ '@site/docs/testing-resources.md'), '@site/docs/testing-resources.md', require.resolveWeak('@site/docs/testing-resources.md')],
  'ec1ff972': [() => import(/* webpackChunkName: 'ec1ff972' */ '@site/docs/keycloak-auth-token-configuration.md'), '@site/docs/keycloak-auth-token-configuration.md', require.resolveWeak('@site/docs/keycloak-auth-token-configuration.md')],};
