/*
 * Copyright 2021-2024 Ona Systems, Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.smartregister.fhircore.quest.sdk

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking

// Testing helper: Borrowed from the FHIR SDK repository package
// https://github.com/google/android-fhir/blob/master/workflow/src/test/java/com/google/android/fhir/workflow/TestingUtil.kt
// DO NOT Edit this file. Updates should be complete overwrites to reflects updates on SDK repo
// In future once the SDK team publishes the workflow-testing module this package will no longer be
// required

internal fun <T> runBlockingOnWorkerThread(block: suspend (CoroutineScope) -> T) =
  runBlocking(Dispatchers.IO) { block(this) }
