# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: ANC APK Release

on:
 workflow_dispatch:
  inputs:
    tags:
      description: 'Github tag'     
      required: true
      default: 'v1.x.x-anc'

env:
 FHIRCORE_USERNAME: ${{ secrets.FHIRCORE_USERNAME }}
 FHIRCORE_ACCESS_TOKEN: ${{ secrets.FHIRCORE_ACCESS_TOKEN }}
 CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 
 KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
 KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
 KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          
      - name: Decode Keystore file
        run: echo $ENCODED_KEYSTORE | base64 -di > "${HOME}"/fhircore.keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_FILE }}  

      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: android
 
      - name: Spotless check anc application
        run: ./gradlew :anc:spotlessCheck
        working-directory: android

      - name: Generate AAB (Android App Bundle) file
        if: ${{ false }}
        run: ./gradlew :anc:bundleRelease -x :anc:testDebugUnitTest --stacktrace
        working-directory: android
        
      - name: Upload AAB file to tag assets
        if: ${{ false }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: android/anc/build/outputs/bundle/release/anc-release.aab
          asset_name: "${{ github.event.inputs.tags }}.aab"
          tag: ${{ github.event.inputs.tags }}
          overwrite: true
      
      - name: Generate APK (Android App PacKage) file
        run: ./gradlew :anc:assembleRelease -x :anc:testDebugUnitTest --stacktrace
        working-directory: android
        
      - name: Upload APK file to tag assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: android/anc/build/outputs/apk/release/anc-release.apk
          asset_name: "${{ github.event.inputs.tags }}.apk"
          tag: ${{ github.event.inputs.tags }}
          prerelease: ${{ contains(github.event.inputs.tags, '-alpha') || contains(github.event.inputs.tags, '-beta') }}
          overwrite: true
