# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: android

    - name: Spotless check
      run: ./gradlew spotlessCheck
      working-directory: android

    - name: Clone the google/android-fhir SDK
      run: cd .. && git clone https://github.com/google/android-fhir.git && cd android-fhir && git checkout ek/sdc-structure-map-extraction-implementation

    - name: Deploy the latest datacapture
      run: cd ../android-fhir && sed -i 's/data-capture/datacapture/g' datacapture/build.gradle.kts && sed -i 's/0.1.0-alpha03/0.2.6-alpha02/g' datacapture/build.gradle.kts && ./gradlew :datacapture:publishToMavenLocal && cd ../fhircore

    - name: Deploy the latest android-fhir engine
      run: cd ../android-fhir && sed -i 's/0.1.0-alpha02/0.1.0-local03/g' engine/build.gradle.kts && sed -i 's/engine:0.0.2/engine:0.1.0-local03/g' ../fhircore/android/app/build.gradle && ./gradlew :engine:publishToMavenLocal && cd ../fhircore

    - name: Run unit tests with Gradle
      run: ./gradlew jacocoTestReport --stacktrace --debug
      working-directory: android
      env:
       FHIRCORE_USERNAME: ${{ secrets.FHIRCORE_USERNAME }}
       FHIRCORE_ACCESS_TOKEN: ${{ secrets.FHIRCORE_ACCESS_TOKEN }}

    - name: Upload code coverage report to coveralls
      run: ./gradlew coveralls --stacktrace
      working-directory: android
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
